version: "3"

services:
  g-rancher2:
    build: ./build/rancher2
    env_file: 
      - ./env/rancher2/default.env
    image: g-rancher2:1.0.0
    container_name: g-rancher2
    restart: always
    ports:
      - 60080:80
      - 60443:443
    volumes:
      - ./data-volumes/rancher2/share-file:/share-file
