version: "3"

services:
  g-zookeeper:
    build: zookeeper/build/zookeeper
    env_file: 
      - zookeeper/env/zookeeper/default.env
    image: g-zookeeper:1.0.0
    container_name: g-zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - ./data-volumes/zookeeper/share-file:/share-file
  g-zkui:
    build: zkui/build/zkui
    env_file:
      - zkui/env/zkui/default.env
    image: g-zkui:1.0.0
    container_name: g-zkui
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./data-volumes/zkui/share-file:/share-file