version: "3"

services:
  g-zookeeper:
    build: ./build/zookeeper
    env_file: 
      - ./env/zookeeper/default.env
    network_mode: "host"
    image: g-zookeeper:1.0.0
    container_name: g-zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - ./data-volumes/zookeeper/share-file:/share-file