version: "3"

services:
  g-influxdb:
    build: ./build/influxdb
    env_file: 
      - ./env/influxdb/default.env
    image: g-influxdb:1.0.0
    container_name: g-influxdb
    restart: always
    ports:
      - 18086:8086
    volumes:
      - ./data-volumes/influxdb/share-file:/share-file
      - ./data-volumes/influxdb/db-data:/var/lib/influxdb
